# Obtained form 
[general]
import = [
	"~/.config/alacritty/themes/catppuccin_mocha"
]

[terminal]
shell.program = "/usr/bin/tmux"
shell.args = ["new", "-A", "-s", "dev"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

opacity = 0.9

option_as_alt = "Both"

dimensions.columns = 100
dimensions.lines = 30

startup_mode = "Maximized"

[font]
normal.family = "MesloLGS NF"
normal.style = "Regular"

bold.family = "MesloLGS NF"
bold.style = "Bold"

italic.family = "MesloLGS NF"
italic.style = "Italic"

bold_italic.family = "MesloLGS NF"
bold_italic.style = "Bold Italic"

size = 12
