[general]
import = [
	"~/.config/alacritty/themes/catppuccin_mocha"
]

[terminal]
shell.program = "/usr/bin/tmux"
shell.args = ["new", "-A", "-s", "dev"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

opacity = 0.9

option_as_alt = "Both"

startup_mode = "Maximized"

padding.x = 0
padding.y = 0
dynamic_padding = true

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 13 # 13 for JetBrains
offset.y = 2 # 1.2 for JetBrains
