[general]
import = [
	"~/.config/alacritty/themes/catppuccin_mocha"
]

[terminal]
shell.program = "/usr/bin/tmux"
shell.args = ["new", "-A", "-s", "dev"]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"

opacity = 0.9

option_as_alt = "Both"

dimensions.columns = 100
dimensions.lines = 30

startup_mode = "Maximized"

[font]
# https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Medium/JetBrainsMonoNerdFontMono-Medium.ttf
normal.family = "JetBrainsMono Nerd Font Mono"

size = 13 # 13 for JetBrains
offset.y = 1 # 1.2 for JetBrains
